#!/usr/bin/env python3
"""Generate the W3D chunk-id -> name table from the engine's own w3d_file.h.

The table is derived, never hand-maintained: if the enum changes, the tool follows. Values are
resolved the way C enumerators are, so the entries that rely on implicit `previous + 1` (most of
the sub-chunk ids) come out right.

Usage: gen_chunk_names.py <path to w3d_file.h> <output .h>
"""

import pathlib
import re
import sys

ENUMERATOR = re.compile(r"^\s*((?:OBSOLETE_)?[A-Z][A-Z0-9_]*)\s*(?:=\s*([^,]+?))?\s*,?\s*(?://.*)?$")


def parse_enums(text):
    """Return {name: value} for every enumerator in every anonymous/named enum block."""
    values = {}
    depth = 0
    in_enum = False
    next_value = 0

    # Strip block comments so their contents cannot look like enumerators.
    text = re.sub(r"/\*.*?\*/", "", text, flags=re.S)

    for line in text.splitlines():
        stripped = line.strip()
        if not in_enum:
            if re.match(r"^(typedef\s+)?enum\b", stripped):
                in_enum = True
                next_value = 0
                depth = stripped.count("{") - stripped.count("}")
            continue

        depth += stripped.count("{") - stripped.count("}")
        if depth <= 0 and "}" in stripped:
            in_enum = False
            continue

        match = ENUMERATOR.match(stripped)
        if not match:
            continue
        name, expression = match.group(1), match.group(2)
        if expression is None:
            value = next_value
        else:
            expression = expression.strip()
            try:
                value = int(eval(expression, {"__builtins__": {}}, dict(values)))  # noqa: S307
            except Exception:
                continue
        values[name] = value
        next_value = value + 1

    return values


def main():
    if len(sys.argv) != 3:
        print(__doc__, file=sys.stderr)
        return 2

    header = pathlib.Path(sys.argv[1]).read_text(errors="replace")
    values = parse_enums(header)
    chunks = {
        name: value
        for name, value in values.items()
        if re.match(r"^(OBSOLETE_)?W3D_CHUNK_", name)
    }
    if not chunks:
        print("no W3D_CHUNK_* enumerators found", file=sys.stderr)
        return 1

    # Several ids are shared by an active name and an OBSOLETE_ alias; prefer the active one.
    by_value = {}
    for name, value in sorted(chunks.items()):
        if value in by_value and by_value[value].startswith("W3D_CHUNK_"):
            continue
        by_value[value] = name

    lines = [
        "// Generated by spikes/assets/tools/gen_chunk_names.py from the engine's w3d_file.h.",
        "// Do not edit.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <string>",
        "",
        "inline std::string w3d_chunk_name(uint32_t id)",
        "{",
        "\tswitch (id) {",
    ]
    for value, name in sorted(by_value.items()):
        lines.append(f'\tcase 0x{value:08X}: return "{name}";')
    lines += [
        "\tdefault: return std::string();",
        "\t}",
        "}",
        "",
        f"inline constexpr int W3D_KNOWN_CHUNK_ID_COUNT = {len(by_value)};",
        "",
    ]

    pathlib.Path(sys.argv[2]).write_text("\n".join(lines))
    print(f"{len(by_value)} chunk ids written to {sys.argv[2]}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
