#!/usr/bin/env python3
"""Generate docs/porting/STATUS.md from the checked-in measurement baselines.

Every other document under docs/porting/ carries hand-typed numbers, and they rot: the plan's
Phase 0 headline survived two slices that changed its denominator, and a probe figure was quoted
that silently depended on an untracked dependency directory. This script exists so that at least
one document cannot rot -- its numbers are read out of the same JSON the CI gates compare against,
never typed.

    python3 scripts/porting-status.py            # rewrite docs/porting/STATUS.md
    python3 scripts/porting-status.py --check    # fail if it is out of date (CI)

Sources, all of them files a gate already reads:

  * docs/porting/ci-baselines/native-port-probe-native.json  -- scripts/ci/check-probe-baseline.py
  * docs/porting/ci-baselines/native-port-probe-shimmed.json -- likewise
  * spikes/renderer/tools/d3d8-direct-allowlist.json         -- scripts/ci/check-d3d8-surface.py

It deliberately does not run any measurement itself: re-measuring belongs to the probe and to the
gates, and a generator that measured would produce a different document on every machine.
"""
import argparse
import json
import pathlib
import sys

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
BASELINES = REPO_ROOT / "docs" / "porting" / "ci-baselines"
ALLOWLIST = REPO_ROOT / "spikes" / "renderer" / "tools" / "d3d8-direct-allowlist.json"
STATUS = REPO_ROOT / "docs" / "porting" / "STATUS.md"

HEADER = """<!-- Generated by scripts/porting-status.py. Do not edit by hand: run the script. -->
# Native port status

Every number here is read out of the measurement baselines the CI gates compare against, so it
cannot drift from what CI enforces. Prose elsewhere under `docs/porting/` may lag; when it
disagrees with this file, this file is right. Regenerate with:

```sh
python3 scripts/porting-status.py
```
"""

FOOTER = """
## What the numbers mean

* **native** -- compiled with `clang++ -fsyntax-only -std=c++20 -m64` with no Windows SDK and no
  header shims. This is the honest "how portable is the source" figure.
* **shimmed** -- the same, with `scripts/native-port-shims/` on the include path. This is the
  "how much can we compile while the seams are still being written" figure, and it is the one that
  moves as slices land.
* **clean / total** -- translation units, not files and not lines. Report the pair, never a bare
  percentage: slices change the denominator.
* **direct D3D8 call sites** -- call sites reaching `IDirect3DDevice8` / `IDirect3D8` outside the
  `DX8CALL*` macros and outside the render backend implementation. The budget is enforced exactly,
  in both directions, by `scripts/ci/check-d3d8-surface.py`.

Measurements are toolchain-sensitive: a different clang gives a different clean count, which is why
CI pins container digests and why the baselines record the major version.

## Reproducing

```sh
./scripts/ci/fetch-probe-deps.sh
CLANGXX=clang++-14 python3 scripts/native-port-probe.py --json probe-native.json
CLANGXX=clang++-14 python3 scripts/native-port-probe.py --with-shims --json probe-shimmed.json
python3 scripts/ci/check-probe-baseline.py --results probe-native.json
python3 scripts/ci/check-probe-baseline.py --results probe-shimmed.json
python3 scripts/ci/check-d3d8-surface.py
```

Scope, phases and estimates: [`native-port-plan.md`](native-port-plan.md). Verified-versus-wrong
claims: [`review-and-decisions.md`](review-and-decisions.md). Concurrent slice ownership:
[`concurrent-slices.md`](concurrent-slices.md).
"""


def load(path):
    if not path.is_file():
        raise SystemExit(f"missing input: {path.relative_to(REPO_ROOT)}")
    return json.loads(path.read_text())


def probe_section(native, shimmed):
    lines = ["", "## Native 64-bit compile readiness", ""]
    clang = native.get("clang_major", "?")
    if shimmed.get("clang_major") != clang:
        raise SystemExit("the two probe baselines were measured with different clang versions")
    lines.append(f"Measured with clang {clang}. Vendor headers present: "
                 f"{', '.join(native.get('deps_present') or ['none'])}.")
    lines += ["", "| Target | Native clean | Shimmed clean |", "|---|---:|---:|"]
    for target, counts in native["targets"].items():
        sh = shimmed["targets"].get(target, {})
        lines.append(f"| `{target}` | {counts['clean']} / {counts['total']} | "
                     f"{sh.get('clean', '?')} / {sh.get('total', counts['total'])} |")
    lines.append(f"| **total** | **{native['clean']} / {native['total']}** | "
                 f"**{shimmed['clean']} / {shimmed['total']}** |")
    return lines


def d3d8_section(allow):
    total = allow.get("total", 0)
    files = allow.get("files") or {}
    lines = ["", "## D3D8 call surface", "",
             f"Direct (non-wrapper, non-backend) call sites permitted: **{total}**."]
    if files:
        lines += ["", "| File | Budget |", "|---|---:|"]
        lines += [f"| `{f}` | {n} |" for f, n in sorted(files.items())]
    else:
        lines.append("No file holds a direct-call budget: every D3D8 call goes through the "
                     "`DX8CALL*` macros or lives inside the render backend implementation.")
    return lines


def render():
    native = load(BASELINES / "native-port-probe-native.json")
    shimmed = load(BASELINES / "native-port-probe-shimmed.json")
    allow = load(ALLOWLIST)
    body = HEADER.splitlines()
    body += probe_section(native, shimmed)
    body += d3d8_section(allow)
    body += FOOTER.splitlines()
    return "\n".join(body).rstrip() + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit non-zero if STATUS.md is out of date")
    args = ap.parse_args()

    want = render()
    rel = STATUS.relative_to(REPO_ROOT)
    if args.check:
        have = STATUS.read_text() if STATUS.is_file() else ""
        if have != want:
            print(f"{rel} is out of date with the baselines: "
                  f"run `python3 scripts/porting-status.py`", file=sys.stderr)
            return 1
        print(f"OK: {rel} matches the baselines")
        return 0
    STATUS.write_text(want)
    print(f"wrote {rel}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
