// Renderer spike: the subset of the Direct3D 8 type vocabulary that the Zero Hour
// engine actually pushes through DX8Wrapper.
//
// These are redeclared here (rather than including d3d8.h) so the spike builds on
// Linux and macOS with no Windows SDK. The values match d3d8types.h, because the
// engine stores raw D3D8 enum values in its own state caches
// (DX8Wrapper::RenderStates[256], TextureStageStates[8][32]) and a real backend has
// to keep accepting them.

#pragma once

#include <cstdint>

namespace spike {

using D3DCOLOR = uint32_t;

enum D3DTRANSFORMSTATETYPE {
	D3DTS_VIEW = 2,
	D3DTS_PROJECTION = 3,
	D3DTS_TEXTURE0 = 16,
	D3DTS_TEXTURE1 = 17,
	D3DTS_TEXTURE2 = 18,
	D3DTS_TEXTURE3 = 19,
	D3DTS_WORLD = 256,
};

// Only the render states the engine actually sets (53 of them; see
// docs/porting/renderer-surface.md). The spike implements the ones needed to draw.
enum D3DRENDERSTATETYPE {
	D3DRS_ZENABLE = 7,
	D3DRS_FILLMODE = 8,
	D3DRS_SHADEMODE = 9,
	D3DRS_ZWRITEENABLE = 14,
	D3DRS_ALPHATESTENABLE = 15,
	D3DRS_SRCBLEND = 19,
	D3DRS_DESTBLEND = 20,
	D3DRS_CULLMODE = 22,
	D3DRS_ZFUNC = 23,
	D3DRS_ALPHAREF = 24,
	D3DRS_ALPHAFUNC = 25,
	D3DRS_DITHERENABLE = 26,
	D3DRS_ALPHABLENDENABLE = 27,
	D3DRS_FOGENABLE = 28,
	D3DRS_SPECULARENABLE = 29,
	D3DRS_FOGCOLOR = 34,
	D3DRS_FOGTABLEMODE = 35,
	D3DRS_FOGSTART = 36,
	D3DRS_FOGEND = 37,
	D3DRS_FOGDENSITY = 38,
	D3DRS_ZBIAS = 47,
	D3DRS_STENCILENABLE = 52,
	D3DRS_STENCILFAIL = 53,
	D3DRS_STENCILZFAIL = 54,
	D3DRS_STENCILPASS = 55,
	D3DRS_STENCILFUNC = 56,
	D3DRS_STENCILREF = 57,
	D3DRS_STENCILMASK = 58,
	D3DRS_STENCILWRITEMASK = 59,
	D3DRS_TEXTUREFACTOR = 60,
	D3DRS_LIGHTING = 137,
	D3DRS_AMBIENT = 139,
	D3DRS_COLORVERTEX = 141,
	D3DRS_COLORWRITEENABLE = 168,
	D3DRS_BLENDOP = 171,
	D3DRS_MAX = 256,
};

enum D3DTEXTURESTAGESTATETYPE {
	D3DTSS_COLOROP = 1,
	D3DTSS_COLORARG1 = 2,
	D3DTSS_COLORARG2 = 3,
	D3DTSS_ALPHAOP = 4,
	D3DTSS_ALPHAARG1 = 5,
	D3DTSS_ALPHAARG2 = 6,
	D3DTSS_ADDRESSU = 13,
	D3DTSS_ADDRESSV = 14,
	D3DTSS_MAGFILTER = 16,
	D3DTSS_MINFILTER = 17,
	D3DTSS_MIPFILTER = 18,
	D3DTSS_TEXCOORDINDEX = 11,
	D3DTSS_TEXTURETRANSFORMFLAGS = 24,
	D3DTSS_COLORARG0 = 26,
	D3DTSS_RESULTARG = 28,
	D3DTSS_MAX = 32,
};

enum D3DTEXTUREOP {
	D3DTOP_DISABLE = 1,
	D3DTOP_SELECTARG1 = 2,
	D3DTOP_SELECTARG2 = 3,
	D3DTOP_MODULATE = 4,
	D3DTOP_MODULATE2X = 5,
	D3DTOP_MODULATE4X = 6,
	D3DTOP_ADD = 7,
	D3DTOP_ADDSIGNED = 8,
	D3DTOP_ADDSIGNED2X = 9,
	D3DTOP_SUBTRACT = 10,
	D3DTOP_ADDSMOOTH = 11,
	D3DTOP_BLENDTEXTUREALPHA = 13,
	D3DTOP_BLENDCURRENTALPHA = 16,
	D3DTOP_DOTPRODUCT3 = 24,
	D3DTOP_MULTIPLYADD = 25,
};

enum D3DTEXTUREARG {
	D3DTA_DIFFUSE = 0,
	D3DTA_CURRENT = 1,
	D3DTA_TEXTURE = 2,
	D3DTA_TFACTOR = 3,
	D3DTA_SPECULAR = 4,
	D3DTA_COMPLEMENT = 0x10,
	D3DTA_ALPHAREPLICATE = 0x20,
	D3DTA_SELECTMASK = 0x0f,
};

enum D3DBLEND {
	D3DBLEND_ZERO = 1,
	D3DBLEND_ONE = 2,
	D3DBLEND_SRCCOLOR = 3,
	D3DBLEND_INVSRCCOLOR = 4,
	D3DBLEND_SRCALPHA = 5,
	D3DBLEND_INVSRCALPHA = 6,
	D3DBLEND_DESTALPHA = 7,
	D3DBLEND_INVDESTALPHA = 8,
	D3DBLEND_DESTCOLOR = 9,
	D3DBLEND_INVDESTCOLOR = 10,
	D3DBLEND_SRCALPHASAT = 11,
};

enum D3DCMPFUNC {
	D3DCMP_NEVER = 1,
	D3DCMP_LESS = 2,
	D3DCMP_EQUAL = 3,
	D3DCMP_LESSEQUAL = 4,
	D3DCMP_GREATER = 5,
	D3DCMP_NOTEQUAL = 6,
	D3DCMP_GREATEREQUAL = 7,
	D3DCMP_ALWAYS = 8,
};

enum D3DCULL {
	D3DCULL_NONE = 1,
	D3DCULL_CW = 2,
	D3DCULL_CCW = 3,
};

enum D3DFILLMODE {
	D3DFILL_POINT = 1,
	D3DFILL_WIREFRAME = 2,
	D3DFILL_SOLID = 3,
};

enum D3DTEXTUREADDRESS {
	D3DTADDRESS_WRAP = 1,
	D3DTADDRESS_MIRROR = 2,
	D3DTADDRESS_CLAMP = 3,
	D3DTADDRESS_BORDER = 4,
};

enum D3DTEXTUREFILTERTYPE {
	D3DTEXF_NONE = 0,
	D3DTEXF_POINT = 1,
	D3DTEXF_LINEAR = 2,
	D3DTEXF_ANISOTROPIC = 3,
};

enum D3DPRIMITIVETYPE {
	D3DPT_POINTLIST = 1,
	D3DPT_LINELIST = 2,
	D3DPT_LINESTRIP = 3,
	D3DPT_TRIANGLELIST = 4,
	D3DPT_TRIANGLESTRIP = 5,
	D3DPT_TRIANGLEFAN = 6,
};

// Flexible vertex format bits. The engine passes these straight to
// IDirect3DDevice8::SetVertexShader when it wants the fixed-function pipeline,
// which is the single nastiest thing to retarget (see the doc).
enum {
	D3DFVF_XYZ = 0x002,
	D3DFVF_XYZRHW = 0x004,
	D3DFVF_XYZB1 = 0x006,
	D3DFVF_XYZB4 = 0x00c,
	D3DFVF_NORMAL = 0x010,
	D3DFVF_DIFFUSE = 0x040,
	D3DFVF_SPECULAR = 0x080,
	D3DFVF_TEX1 = 0x100,
	D3DFVF_TEX2 = 0x200,
	D3DFVF_TEX3 = 0x300,
	D3DFVF_TEX4 = 0x400,
	D3DFVF_TEXCOUNT_MASK = 0xf00,
	D3DFVF_TEXCOUNT_SHIFT = 8,
	D3DFVF_POSITION_MASK = 0x00e,
};

} // namespace spike
